### ISSUE TITLE
It seems there is a null dereference. 

### ISSUE THREAD

**Issue by mlite** [gnuless/ncc#1]
DTS_MSG: Stensal DTS detected a fatal program error!
DTS_MSG: Continuing the execution will cause unexpected behaviors, abort!
DTS_MSG: dereference an uninitialized value as pointer: 0xc
DTS_MSG: Diagnostic infomation:

- Stack trace (most recent call first):
-[1]  file:/home/sbuilder/workspace/ncc/ncpp/token.c::474, 13
-[2]  file:/home/sbuilder/workspace/ncc/ncpp/ncpp.c::176, 5
-[3]  file:/home/sbuilder/workspace/ncc/ncpp/ncpp.c::292, 18
-[4]  file:/home/nwang/acore/musl/src/env/__libc_start_main.c::180, 11

**Comment by gnuless** [comment]
Whoops. Looks like new_token() never explicitly returned the token it allocated. Fixed.
